apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
      annotations:
      {{- range $key, $value := .Values.api.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      containers:
      - env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: {{ .Values.api.image }}:{{ .Values.codecovVersion }}
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: {{ .Values.api.port }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ .Values.api.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: 
          limits:
            cpu: {{ .Values.api.resources.limits.cpu }}
            memory: {{ .Values.api.resources.limits.memory }}
          requests:
            cpu: {{ .Values.api.resources.requests.cpu }}
            memory: {{ .Values.api.resources.requests.memory }}
        volumeMounts:
        - mountPath: /config
          name: codecov-yml
          readOnly: true
        - mountPath: /cert
          name: scm-ca-cert
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: codecov-yml
        secret:
          secretName: codecov-yml
      - name: scm-ca-cert
        secret:
          secretName: scm-ca-cert
