apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  name: api
spec:
  ports:
  - port: {{ .Values.api.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.api.port }}
  selector:
    app: api
  type: NodePort
