apiVersion: v1
kind: Secret
metadata:
  name: codecov-yml
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
data:
  codecov.yml: {{ .Values.codecovYaml | b64enc | quote }}
